CREATE TABLE Buildings(
	Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Capacity INT NOT NULL CHECK (Capacity >= 1),
);

CREATE TABLE AddressLocations(
	Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	StreetName NVARCHAR(50) NOT NULL,
	StreetNumber INT NOT NULL CHECK(StreetNumber >= 1),
	PostalCode NVARCHAR(50) NOT NULL,
	City NVARCHAR(50) NOT NULL,
	BuildingId INT NOT NULL FOREIGN KEY REFERENCES Buildings(Id),
);

CREATE TABLE Apartments(
	Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	NumberInBuilding INT NOT NULL CHECK (NumberInBuilding >= 1),
	Residents INT NOT NULL DEFAULT(0),
	SurfaceArea FLOAT NOT NULL,
	BuildingId INT NOT NULL FOREIGN KEY REFERENCES Buildings(Id),
);

CREATE TABLE Tenants(
	Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	ApartmentId INT NOT NULL FOREIGN KEY REFERENCES Apartments(Id),
);